# Generated by Django 5.0.2 on 2024-03-16 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_myuser_first_name_alter_myuser_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(upload_to='')),
                ('phone_number', models.CharField(max_length=11)),
                ('med_cetificate', models.ImageField(default=None, upload_to='')),
                ('location', models.CharField(max_length=255)),
                ('otp_verified', models.BooleanField(default=False)),
                ('kyc_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(upload_to='')),
                ('phone_number', models.CharField(max_length=11)),
                ('location', models.CharField(max_length=255)),
                ('medical_history', models.CharField(max_length=255)),
                ('otp_verified', models.BooleanField(default=False)),
                ('kyc_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='identity',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor')], max_length=15),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
